# fly.toml app configuration file generated for ai-mock-interview on 2025-05-04T16:43:50-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-mock-interview'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'
  FRONTEND_PORT = '3000'

# Main service configuration
[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

  [[http_service.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[http_service.ports]]
    port = 443
    handlers = ["tls", "http"]

  [http_service.http_options]
    compression = true

# API service is exposed through the same VM
# but will be accessible at the /api path

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
